### ISSUE TITLE
Xfce panel style

### ISSUE THREAD

**Issue by matteoalessiocarrara** [nana-4/Flat-Plat#60]
I'm on xfce 4:12, but I think it also concerns other d.e. . The panel has the same style of gtk theme, which is cute but a bit monotonous. I thought that you could adopt a different style for the panels, maybe a dark color, to make it a little differently.
![screenshot_2016-08-12_12-09-08](https://cloud.githubusercontent.com/assets/7833001/17619419/9e7b0662-6085-11e6-8caa-87d7f5412117.png)
![screenshot_2016-08-12_12-08-39](https://cloud.githubusercontent.com/assets/7833001/17619420/9e7df58e-6085-11e6-920c-16803efcb079.png)

**Comment by nana-4** [comment]
Flat-Plat is currently not supported Xfce, but I will support it if I have time.

**Comment by bodqhrohro** [comment]
After moving Xfce4-panel to GTK+3 (currently have 4.12.1 on Debian Testing) there appeared a static top padding in the datetime applet. This padding does not depend on font size and does not reproduce with other themes.
![2016-11-20-142427_1366x768_scrot](https://cloud.githubusercontent.com/assets/2134486/20462759/fe5137ae-af2d-11e6-8e6c-c5bddcae962c.png)

**Comment by nana-4** [comment]
I added initial implementation for Xfce theming (GTK3), although it's not yet perfect. (Supporting for GTK2 version is also not yet.)

Tested on Xfce 4.13 (Ubuntu 18.10)

**Comment by nana-4** [comment]
**TODO:**
- [ ] GTK3: FIx `#XfceNotifyWindow` styling
- [ ] GTK3: FIx `#xfwm-tabwin` styling
- [ ] Xfwm4: Change frame width to 2px
- [ ] Xfwm4: Change corner radius to 4px
- [ ] GTK2: Support Xfce 4.12 (hopefully)

**Comment by DarthWound** [comment]
Hello @nana-4 

For xfce4-panel _(v4.12 GTK2)_ on standard Materia, I suggest you to use bits from Materia-dark and change panel background to `#333333`.

Here's what it looks like _(I'm using dark variant + `#333` panel bg)_, don't care about the green colors I customized theme to fit the distro:
![capture](https://user-images.githubusercontent.com/1771322/52475118-c44f4c80-2b9a-11e9-84ea-0d38a30917ef.PNG)

Currently, standard variant panel _(with panel bg using theme defaults)_ is like this:
![capture1](https://user-images.githubusercontent.com/1771322/52475383-9c141d80-2b9b-11e9-9590-71b1fcada25f.PNG)
BTW, light variant is the same except that dark grey parts are black.

Keep up the good work, Xfce full support would be great. Of course GTK3 will probably come this year, but a lot of distros will be on <4.14 for quite a long time _(Ubuntu LTS, Debian, other slow point releases...)_.

**Comment by nana-4** [comment]
Hi @DarthWound, thanks for your suggestion.

I agree that Materia should support v4.12 as well. But [Materia uses `#212121` instead of `#383838` for panels by default](https://github.com/nana-4/materia-theme/blob/fedc9a73cb728b34ee358ea9083685cf6e7f929b/src/_sass/_colors.scss#L61). So I'd choose that color unless there is any special reason :)

**Comment by DarthWound** [comment]
Thanks, didn't see the "panel" line in `colors.scss` :)

**Comment by charbelnicolas** [comment]
The materia theme looks beautiful on XFCE, but I was just wondering if it is possible to add a margin to some of the panel buttons so it doesn't look too crowded? or add some padding to the parent panel? Is it possible to modify this?

![Screenshot_2019-09-06_22-07-20](https://user-images.githubusercontent.com/14960414/64469216-c73ffa80-d0f3-11e9-9ee8-271790641e36.jpg)

Please see the attached image so you can understand what I mean.

Thanks in advance...

**Comment by charbelnicolas** [comment]
![padding](https://user-images.githubusercontent.com/14960414/64469302-2a7e5c80-d0f5-11e9-8cfd-ac0cb9472b8a.jpg)

If would be nice to know if there is a way to make all the buttons behave in the same way as it is with the lightdm gtk greeter settings.
